import { Puzzle } from '@/types';

export const mockPuzzle: Puzzle = {
  "id": "mini-7x7-custom",
  "title": "Heritage Stackers Daily Mini Crossword",
  "date": "2026-06-26",
  "clues": [
    { "number": 1, "direction": "across", "text": "Companions or guides who accompany others.", "answer": "ESCORTS", "row": 0, "col": 0 },
    { "number": 8, "direction": "across", "text": "___ Spiegel (German magazine).", "answer": "DER", "row": 1, "col": 0 },
    { "number": 9, "direction": "across", "text": "A major division of time.", "answer": "ERA", "row": 1, "col": 4 },
    { "number": 10, "direction": "across", "text": "Given medical care or attention.", "answer": "TREATED", "row": 2, "col": 0 },
    { "number": 13, "direction": "across", "text": "The importance, worth, or usefulness of something.", "answer": "VALUE", "row": 3, "col": 1 },
    { "number": 14, "direction": "across", "text": "A small piece or quantity of something.", "answer": "BIT", "row": 4, "col": 0 },
    { "number": 15, "direction": "across", "text": "Really Simple Syndication (Abbr.).", "answer": "RSS", "row": 4, "col": 4 },
    { "number": 16, "direction": "across", "text": "A very large expanse of sea.", "answer": "OCEAN", "row": 5, "col": 0 },
    { "number": 17, "direction": "across", "text": "The ninth letter of the alphabet.", "answer": "I", "row": 5, "col": 6 },
    { "number": 18, "direction": "across", "text": "To join in marriage.", "answer": "WED", "row": 6, "col": 0 },
    { "number": 19, "direction": "across", "text": "To perceive with the eyes.", "answer": "SEE", "row": 6, "col": 4 },
    
    { "number": 1, "direction": "down", "text": "Eastern Daylight Time (Abbr.).", "answer": "EDT", "row": 0, "col": 0 },
    { "number": 2, "direction": "down", "text": "The action of helping or doing work for someone.", "answer": "SERVICE", "row": 0, "col": 1 },
    { "number": 3, "direction": "down", "text": "Brought into existence.", "answer": "CREATED", "row": 0, "col": 2 },
    { "number": 4, "direction": "down", "text": "The fifteenth letter of the alphabet.", "answer": "O", "row": 0, "col": 3 },
    { "number": 5, "direction": "down", "text": "Comes back to a place or person.", "answer": "RETURNS", "row": 0, "col": 4 },
    { "number": 6, "direction": "down", "text": "Woody perennial plants.", "answer": "TREES", "row": 0, "col": 5 },
    { "number": 7, "direction": "down", "text": "Feeling or showing sorrow.", "answer": "SAD", "row": 0, "col": 6 },
    { "number": 11, "direction": "down", "text": "Pacino or Yankovic.", "answer": "AL", "row": 2, "col": 3 },
    { "number": 12, "direction": "down", "text": "A knot tied with two loops.", "answer": "BOW", "row": 4, "col": 0 },
    { "number": 15, "direction": "down", "text": "German pronoun for 'she' or 'they'.", "answer": "SIE", "row": 4, "col": 6 },
    { "number": 16, "direction": "down", "text": "The first letter of the alphabet.", "answer": "A", "row": 5, "col": 3 },
    { "number": 17, "direction": "down", "text": "The fifth letter of the alphabet.", "answer": "E", "row": 6, "col": 5 }
  ],
  "grid": [
    [ { "row": 0, "col": 0, "value": "", "answer": "E", "isBlack": false, "number": 1 },
      { "row": 0, "col": 1, "value": "", "answer": "S", "isBlack": false, "number": 2 },
      { "row": 0, "col": 2, "value": "", "answer": "C", "isBlack": false, "number": 3 },
      { "row": 0, "col": 3, "value": "", "answer": "O", "isBlack": false, "number": 4 },
      { "row": 0, "col": 4, "value": "", "answer": "R", "isBlack": false, "number": 5 },
      { "row": 0, "col": 5, "value": "", "answer": "T", "isBlack": false, "number": 6 },
      { "row": 0, "col": 6, "value": "", "answer": "S", "isBlack": false, "number": 7 } ],
    [ { "row": 1, "col": 0, "value": "", "answer": "D", "isBlack": false, "number": 8 },
      { "row": 1, "col": 1, "value": "", "answer": "E", "isBlack": false },
      { "row": 1, "col": 2, "value": "", "answer": "R", "isBlack": false },
      { "row": 1, "col": 3, "value": "", "answer": "", "isBlack": true },
      { "row": 1, "col": 4, "value": "", "answer": "E", "isBlack": false, "number": 9 },
      { "row": 1, "col": 5, "value": "", "answer": "R", "isBlack": false },
      { "row": 1, "col": 6, "value": "", "answer": "A", "isBlack": false } ],
    [ { "row": 2, "col": 0, "value": "", "answer": "T", "isBlack": false, "number": 10 },
      { "row": 2, "col": 1, "value": "", "answer": "R", "isBlack": false },
      { "row": 2, "col": 2, "value": "", "answer": "E", "isBlack": false },
      { "row": 2, "col": 3, "value": "", "answer": "A", "isBlack": false, "number": 11 },
      { "row": 2, "col": 4, "value": "", "answer": "T", "isBlack": false },
      { "row": 2, "col": 5, "value": "", "answer": "E", "isBlack": false },
      { "row": 2, "col": 6, "value": "", "answer": "D", "isBlack": false } ],
    [ { "row": 3, "col": 0, "value": "", "answer": "", "isBlack": true },
      { "row": 3, "col": 1, "value": "", "answer": "V", "isBlack": false, "number": 13 },
      { "row": 3, "col": 2, "value": "", "answer": "A", "isBlack": false },
      { "row": 3, "col": 3, "value": "", "answer": "L", "isBlack": false },
      { "row": 3, "col": 4, "value": "", "answer": "U", "isBlack": false },
      { "row": 3, "col": 5, "value": "", "answer": "E", "isBlack": false },
      { "row": 3, "col": 6, "value": "", "answer": "", "isBlack": true } ],
    [ { "row": 4, "col": 0, "value": "", "answer": "B", "isBlack": false, "number": 12 },
      { "row": 4, "col": 1, "value": "", "answer": "I", "isBlack": false, "number": 14 },
      { "row": 4, "col": 2, "value": "", "answer": "T", "isBlack": false },
      { "row": 4, "col": 3, "value": "", "answer": "", "isBlack": true },
      { "row": 4, "col": 4, "value": "", "answer": "R", "isBlack": false, "number": 15 },
      { "row": 4, "col": 5, "value": "", "answer": "S", "isBlack": false },
      { "row": 4, "col": 6, "value": "", "answer": "S", "isBlack": false } ],
    [ { "row": 5, "col": 0, "value": "", "answer": "O", "isBlack": false, "number": 16 },
      { "row": 5, "col": 1, "value": "", "answer": "C", "isBlack": false },
      { "row": 5, "col": 2, "value": "", "answer": "E", "isBlack": false },
      { "row": 5, "col": 3, "value": "", "answer": "A", "isBlack": false, "number": 16 },
      { "row": 5, "col": 4, "value": "", "answer": "N", "isBlack": false },
      { "row": 5, "col": 5, "value": "", "answer": "", "isBlack": true },
      { "row": 5, "col": 6, "value": "", "answer": "I", "isBlack": false, "number": 17 } ],
    [ { "row": 6, "col": 0, "value": "", "answer": "W", "isBlack": false, "number": 18 },
      { "row": 6, "col": 1, "value": "", "answer": "E", "isBlack": false },
      { "row": 6, "col": 2, "value": "", "answer": "D", "isBlack": false },
      { "row": 6, "col": 3, "value": "", "answer": "", "isBlack": true },
      { "row": 6, "col": 4, "value": "", "answer": "S", "isBlack": false, "number": 19 },
      { "row": 6, "col": 5, "value": "", "answer": "E", "isBlack": false, "number": 17 },
      { "row": 6, "col": 6, "value": "", "answer": "E", "isBlack": false } ]
  ]
};
